POST {{url}}/api/v1/starter.zip
Accept: application/zip
Content-Type: application/json

{
  "projectName": "projectname",
  "groupId": "com.softwaremill",
  "effect": "FutureEffect",
  "implementation": "Akka",
  "addDocumentation": true,
  "addMetrics": true,
  "json": "Jsoniter",
  "scalaVersion": "Scala2",
  "builder": "Sbt"
}
