POST {{url}}/starter.zip
Accept: application/octet-stream
Content-Type: application/json

{
  "projectName" : "projectname",
  "groupId" : "softwaremill.com",
  "effect" : {
    "FutureEffect" : {

    }
  },
  "implementation" : {
    "Akka" : {

    }
  },
  "tapirVersion" : "1.0.0-RC1"
}

###
