version: 1
labels:
  - label: "automerge"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/plugins.sbt"
  - label: "automerge"
    authors: ["dependabot"]
    files:
      - "ui/yarn.lock"
  - label: "dependency"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/plugins.sbt"
