pull_request_rules:
  - name: delete head branch after merge
    conditions: [ ]
    actions:
      delete_head_branch: { }
  - name: automatic merge for softwaremill-ci pull requests affecting build.sbt
    conditions:
      - author=softwaremill-ci
      - check-success=verify_unit_tests_lint
      - check-success=verify_integration (Scala2, No)
      - check-success=verify_integration (Scala2, Circe)
      - check-success=verify_integration (Scala2, Jsoniter)
      - check-success=verify_integration (Scala2, ZIOJson)
      - check-success=verify_integration (Scala3, No)
      - check-success=verify_integration (Scala3, Circe)
      - check-success=verify_integration (Scala3, Jsoniter)
      - check-success=verify_integration (Scala3, ZIOJson)
      - check-success=verify_docker_image_build
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for softwaremill-ci pull requests affecting project plugins.sbt
    conditions:
      - author=softwaremill-ci
      - check-success=verify_unit_tests_lint
      - check-success=verify_integration (Scala2, No)
      - check-success=verify_integration (Scala2, Circe)
      - check-success=verify_integration (Scala2, Jsoniter)
      - check-success=verify_integration (Scala2, ZIOJson)
      - check-success=verify_integration (Scala3, No)
      - check-success=verify_integration (Scala3, Circe)
      - check-success=verify_integration (Scala3, Jsoniter)
      - check-success=verify_integration (Scala3, ZIOJson)
      - check-success=verify_docker_image_build
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
  - name: semi-automatic merge for softwaremill-ci pull requests
    conditions:
      - author=softwaremill-ci
      - check-success=verify_unit_tests_lint
      - check-success=verify_integration (Scala2, No)
      - check-success=verify_integration (Scala2, Circe)
      - check-success=verify_integration (Scala2, Jsoniter)
      - check-success=verify_integration (Scala2, ZIOJson)
      - check-success=verify_integration (Scala3, No)
      - check-success=verify_integration (Scala3, Circe)
      - check-success=verify_integration (Scala3, Jsoniter)
      - check-success=verify_integration (Scala3, ZIOJson)
      - check-success=verify_docker_image_build
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for softwaremill-ci pull requests affecting project build.properties
    conditions:
      - author=softwaremill-ci
      - check-success=verify_unit_tests_lint
      - check-success=verify_integration (Scala2, No)
      - check-success=verify_integration (Scala2, Circe)
      - check-success=verify_integration (Scala2, Jsoniter)
      - check-success=verify_integration (Scala2, ZIOJson)
      - check-success=verify_integration (Scala3, No)
      - check-success=verify_integration (Scala3, Circe)
      - check-success=verify_integration (Scala3, Jsoniter)
      - check-success=verify_integration (Scala3, ZIOJson)
      - check-success=verify_docker_image_build
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
  - name: automatic merge for softwaremill-ci pull requests affecting .scalafmt.conf
    conditions:
      - author=softwaremill-ci
      - check-success=verify_unit_tests_lint
      - check-success=verify_integration (Scala2, No)
      - check-success=verify_integration (Scala2, Circe)
      - check-success=verify_integration (Scala2, Jsoniter)
      - check-success=verify_integration (Scala2, ZIOJson)
      - check-success=verify_integration (Scala3, No)
      - check-success=verify_integration (Scala3, Circe)
      - check-success=verify_integration (Scala3, Jsoniter)
      - check-success=verify_integration (Scala3, ZIOJson)
      - check-success=verify_docker_image_build
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
